# Generated by Django 3.2.11 on 2022-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='time',
            field=models.TimeField(blank=True, default='22:04:28', null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.CharField(help_text="Enter reciever's email address", max_length=100),
        ),
        migrations.AlterField(
            model_name='mail',
            name='name',
            field=models.CharField(help_text="Enter reciever's name", max_length=100),
        ),
    ]
