# Generated by Django 3.2.4 on 2022-01-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_email', '0004_alter_mail_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='time',
            field=models.TimeField(blank=True, default='12:12:24', null=True),
        ),
    ]
